server {
    listen 80;
    server_name cdn.spoekle.com;

    # Redirect /images/ requests to /api/cdn/images/
    location ^~ /images/ {
        rewrite ^/images/(.*) /api/cdn/images/$1 break;
        proxy_pass http://api:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        client_max_body_size 3000M;
        
        # Set caching headers
        add_header Cache-Control "public, max-age=86400";
        
        # Add CORS headers
        add_header 'Access-Control-Allow-Origin' 'https://spoekle.com';
        add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
    }

    location / {
        proxy_pass http://api:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        client_max_body_size 3000M;

        add_header Cache-Control "public, max-age=86400";
        
        # Add CORS headers
        add_header 'Access-Control-Allow-Origin' 'https://spoekle.com';
        add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
    }
    
    # Special caching for photo thumbnails
    location /images/photos/thumbnails/ {
        proxy_pass http://api:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        
        # Aggressive caching for thumbnails
        add_header Cache-Control "public, max-age=604800";  # 7 days
        
        # Add CORS headers
        add_header 'Access-Control-Allow-Origin' 'https://spoekle.com';
        add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
    }
}
